{
    'name':"VVC",
    'description': 'Vehicles Validation Certificates App',
    'author':"Alaa",
    'version':'1.0',
    'data':[
        'security/vvc_groups.xml',
        'security/ir.model.access.csv',
        'views/vvc_certificates_views.xml',
        'views/vvc_certificate_types_views.xml',
        'views/vvc_traffic_department_views.xml',
        'views/vvc_customers_views.xml',
        'views/vvc_brand_views.xml',
        'views/res_partner_customers_inherit_views.xml',
        'reports/vvc_certificate_template.xml',
        'reports/reports.xml'
    ],
    'installable':True,
    'auto_install':False,
    'license':'AGPL-3',
}